window.PRODUCTS = [
  {
    "name": "Nike Pegasus 42",
    "brand": "Nike",
    "category": "Running Shoes",
    "sub": "Daily Trainer",
    "price": 155.0,
    "old": null,
    "color": "White / Volt",
    "audience": "Men",
    "source": "Nike",
    "url": "https://www.nike.com/us/es/w/pegasus-road-running-calzado-3qxw3z8nexhzy7ok",
    "accent": "#b8ff2c",
    "image": "assets/products/product-01.jpg",
    "id": 0
  },
  {
    "name": "Nike Vaporfly 4",
    "brand": "Nike",
    "category": "Running Shoes",
    "sub": "Race Day",
    "price": 199.97,
    "old": 270.0,
    "color": "Pulse / Orange",
    "audience": "Women",
    "source": "Nike",
    "url": "https://www.nike.com/us/es/t/tenis-de-carrera-en-pavimento-para-mujer-nike-vaporfly-4-hVz16nSu",
    "accent": "#ff6a24",
    "image": "assets/products/product-02.jpg",
    "id": 1
  },
  {
    "name": "adidas Adizero Boston 13",
    "brand": "adidas",
    "category": "Running Shoes",
    "sub": "Speed Trainer",
    "price": 160.0,
    "old": null,
    "color": "Core Black / White",
    "audience": "Men",
    "source": "adidas",
    "url": "https://www.adidas.com/us/adizero_boston-shoes",
    "accent": "#d8ff37",
    "image": "assets/products/product-03.jpg",
    "id": 2
  },
  {
    "name": "adidas Adizero Adios Pro 4",
    "brand": "adidas",
    "category": "Running Shoes",
    "sub": "Race Day",
    "price": 204.0,
    "old": 255.0,
    "color": "White / Black",
    "audience": "Unisex",
    "source": "adidas",
    "url": "https://www.adidas.com/us/adizero_adios_pro_4",
    "accent": "#f3ff56",
    "image": "assets/products/product-04.jpg",
    "id": 3
  },
  {
    "name": "ASICS GEL-NIMBUS 28",
    "brand": "ASICS",
    "category": "Running Shoes",
    "sub": "Max Cushion",
    "price": 170.0,
    "old": null,
    "color": "Blue / White",
    "audience": "Men",
    "source": "ASICS",
    "url": "https://www.asics.com/us/en-us/gel-nimbus/c/aa50102000/",
    "accent": "#3aa9ff",
    "image": "assets/products/product-05.jpg",
    "id": 4
  },
  {
    "name": "ASICS METASPEED SKY TOKYO",
    "brand": "ASICS",
    "category": "Running Shoes",
    "sub": "Race Day",
    "price": 270.0,
    "old": null,
    "color": "Green Gecko / Black",
    "audience": "Unisex",
    "source": "ASICS",
    "url": "https://www.asics.com/us/en-us/metaspeed-sky-tokyo/p/ANA_1013A162-300.html",
    "accent": "#7cff3a",
    "image": "assets/products/product-06.jpg",
    "id": 5
  },
  {
    "name": "Brooks Ghost 18",
    "brand": "Brooks",
    "category": "Running Shoes",
    "sub": "Daily Trainer",
    "price": 150.0,
    "old": null,
    "color": "Black / Lime",
    "audience": "Men",
    "source": "Brooks Running",
    "url": "https://stores.brooksrunning.com/search/running-shoes?sort=price-low-to-high&store=16475&store_id=16475",
    "accent": "#b9ff32",
    "image": "assets/products/product-07.jpg",
    "id": 6
  },
  {
    "name": "HOKA Clifton 10",
    "brand": "HOKA",
    "category": "Running Shoes",
    "sub": "Daily Trainer",
    "price": 154.99,
    "old": null,
    "color": "White / Black",
    "audience": "Women",
    "source": "DICK'S Sporting Goods",
    "url": "https://www.dickssportinggoods.com/p/hoka-womens-clifton-10-running-shoes-25fhqwclftn10blckftw/25fhqwclftn10blckftw",
    "accent": "#67c8ff",
    "image": "assets/products/product-08.jpg",
    "id": 7
  },
  {
    "name": "Saucony Endorphin Speed 5",
    "brand": "Saucony",
    "category": "Running Shoes",
    "sub": "Speed Trainer",
    "price": 175.0,
    "old": null,
    "color": "Black / White",
    "audience": "Men",
    "source": "Nordstrom",
    "url": "https://www.nordstrom.com/s/saucony-endorphin-speed-5-running-shoe-men/8106509",
    "accent": "#fd5d4c",
    "image": "assets/products/product-09.jpg",
    "id": 8
  },
  {
    "name": "New Balance Fresh Foam X 1080v14",
    "brand": "New Balance",
    "category": "Running Shoes",
    "sub": "Max Cushion",
    "price": 169.99,
    "old": null,
    "color": "Earth / Shadow",
    "audience": "Men",
    "source": "New Balance",
    "url": "https://www.newbalance.com/pd/fresh-foam-x-1080v14/M1080V14-47512-PMG-NA-E.html",
    "accent": "#e6c16f",
    "image": "assets/products/product-10.jpg",
    "id": 9
  },
  {
    "name": "On Cloudmonster 3",
    "brand": "On",
    "category": "Running Shoes",
    "sub": "Max Cushion",
    "price": 190.0,
    "old": null,
    "color": "White / Lime",
    "audience": "Unisex",
    "source": "On",
    "url": "https://www.on.com/en-us/shop/shoes/cloudmonster",
    "accent": "#b7ff2e",
    "image": "assets/products/product-11.jpg",
    "id": 10
  },
  {
    "name": "On Cloudboom Strike 2",
    "brand": "On",
    "category": "Running Shoes",
    "sub": "Race Day",
    "price": 250.0,
    "old": null,
    "color": "White / Black",
    "audience": "Unisex",
    "source": "On",
    "url": "https://www.on.com/en-us/shop/shoes/cloudboom",
    "accent": "#ff5c36",
    "image": "assets/products/product-12.jpg",
    "id": 11
  },
  {
    "name": "Nike Everyday Plus Cushioned 6-Pack",
    "brand": "Nike",
    "category": "Socks",
    "sub": "Training Socks",
    "price": 24.97,
    "old": 28.0,
    "color": "Multicolor",
    "audience": "Unisex",
    "source": "Nike",
    "url": "https://www.nike.com/us/es/t/calcetines-al-tobillo-de-entrenamiento-everyday-plus-cushioned-6-pares-xGOLbiOE/SX6899-904",
    "accent": "#f2d45c",
    "image": "assets/products/product-13.jpg",
    "id": 12
  },
  {
    "name": "Feetures Elite Light Cushion Mini Crew 3-Pack",
    "brand": "Feetures",
    "category": "Socks",
    "sub": "Running Socks",
    "price": 59.85,
    "old": 63.0,
    "color": "White Mix",
    "audience": "Unisex",
    "source": "Feetures",
    "url": "https://feetures.com/products/elite-light-cushion-mini-crew-3-pack",
    "accent": "#89d4ff",
    "image": "assets/products/product-14.jpg",
    "id": 13
  },
  {
    "name": "Balega Hidden Comfort No Show",
    "brand": "Balega",
    "category": "Socks",
    "sub": "Running Socks",
    "price": 17.0,
    "old": null,
    "color": "Zesty Lemon",
    "audience": "Unisex",
    "source": "DICK'S Sporting Goods",
    "url": "https://www.dickssportinggoods.com/p/balega-hidden-comfort-no-show-running-socks-16ifouhddncmfrtsmapa/16ifouhddncmfrtsmapa",
    "accent": "#e5ff41",
    "image": "assets/products/product-15.jpg",
    "id": 14
  },
  {
    "name": "Nike Dri-FIT Club Structured Swoosh Cap",
    "brand": "Nike",
    "category": "Hats",
    "sub": "Performance Cap",
    "price": 28.0,
    "old": null,
    "color": "White",
    "audience": "Unisex",
    "source": "Nike",
    "url": "https://www.nike.com/t/dri-fit-club-structured-swoosh-cap-kxvJ3j/FB5625-133",
    "accent": "#eeeeee",
    "image": "assets/products/product-16.jpg",
    "id": 15
  },
  {
    "name": "adidas Running x Adizero CLIMACOOL Cap",
    "brand": "adidas",
    "category": "Hats",
    "sub": "Running Cap",
    "price": 21.0,
    "old": 30.0,
    "color": "Black",
    "audience": "Unisex",
    "source": "adidas",
    "url": "https://www.adidas.com/us/aeroready-cap",
    "accent": "#d5ff35",
    "image": "assets/products/product-17.jpg",
    "id": 16
  },
  {
    "name": "On Lightweight Cap",
    "brand": "On",
    "category": "Hats",
    "sub": "Running Cap",
    "price": 45.0,
    "old": null,
    "color": "Black",
    "audience": "Unisex",
    "source": "On",
    "url": "https://www.on.com/en-us/shop/mens/gifts",
    "accent": "#91d8ff",
    "image": "assets/products/product-18.jpg",
    "id": 17
  },
  {
    "name": "FlipBelt Running Cap",
    "brand": "FlipBelt",
    "category": "Hats",
    "sub": "Running Cap",
    "price": 28.0,
    "old": null,
    "color": "Electric Yellow",
    "audience": "Unisex",
    "source": "FlipBelt",
    "url": "https://flipbelt.com/collections/flipbelt-for-running",
    "accent": "#eaff35",
    "image": "assets/products/product-19.jpg",
    "id": 18
  },
  {
    "name": "goodr Astro G Sunglasses",
    "brand": "goodr",
    "category": "Sunglasses",
    "sub": "Running Sunglasses",
    "price": 45.0,
    "old": null,
    "color": "Chartreuse",
    "audience": "Unisex",
    "source": "Backcountry",
    "url": "https://www.backcountry.com/b/goodr-astro-g-sunglasses",
    "accent": "#c7ff3b",
    "image": "assets/products/product-20.jpg",
    "id": 19
  },
  {
    "name": "goodr Grand G Sunglasses",
    "brand": "goodr",
    "category": "Sunglasses",
    "sub": "Running Sunglasses",
    "price": 35.0,
    "old": null,
    "color": "Red",
    "audience": "Unisex",
    "source": "Backcountry",
    "url": "https://www.backcountry.com/b/goodr-grand-g-sunglasses",
    "accent": "#ff554d",
    "image": "assets/products/product-21.jpg",
    "id": 20
  },
  {
    "name": "FlipBelt Classic Running Belt",
    "brand": "FlipBelt",
    "category": "Belts",
    "sub": "Phone & Key Belt",
    "price": 44.0,
    "old": null,
    "color": "Black",
    "audience": "Unisex",
    "source": "FlipBelt",
    "url": "https://flipbelt.com/products/flipbelt-classic-running-belt",
    "accent": "#b7ff33",
    "image": "assets/products/product-22.jpg",
    "id": 21
  },
  {
    "name": "FlipBelt Zipper Running Belt",
    "brand": "FlipBelt",
    "category": "Belts",
    "sub": "Secure Running Belt",
    "price": 49.0,
    "old": null,
    "color": "Black",
    "audience": "Unisex",
    "source": "FlipBelt",
    "url": "https://flipbelt.com/products/flipbelt-zipper-running-belt",
    "accent": "#73d8ff",
    "image": "assets/products/product-23.jpg",
    "id": 22
  },
  {
    "name": "On Speed Belt",
    "brand": "On",
    "category": "Belts",
    "sub": "Road & Trail Belt",
    "price": 40.0,
    "old": null,
    "color": "Black",
    "audience": "Unisex",
    "source": "On",
    "url": "https://www.on.com/en-us/shop/womens/gifts/running",
    "accent": "#e8ff4d",
    "image": "assets/products/product-24.jpg",
    "id": 23
  },
  {
    "name": "FlipBelt Tahoe Hydration Vest 2.0",
    "brand": "FlipBelt",
    "category": "Hydration",
    "sub": "Hydration Vest",
    "price": 169.0,
    "old": null,
    "color": "Electric Yellow",
    "audience": "Unisex",
    "source": "FlipBelt",
    "url": "https://shop.flipbelt.com/pages/shop-all",
    "accent": "#eaff3a",
    "image": "assets/products/product-25.jpg",
    "id": 24
  },
  {
    "name": "On Soft Flask 500ml",
    "brand": "On",
    "category": "Hydration",
    "sub": "Soft Flask",
    "price": 25.0,
    "old": null,
    "color": "Clear / Black",
    "audience": "Unisex",
    "source": "On",
    "url": "https://www.on.com/en-us/shop/womens/gifts/running",
    "accent": "#69d8ff",
    "image": "assets/products/product-26.jpg",
    "id": 25
  }
];