window.PRODUCTS = [
  {
    "id": 0,
    "name": "Nike Pegasus 42",
    "brand": "Nike",
    "category": "Running Shoes",
    "type": "Daily Trainer",
    "gender": "Men",
    "price": 145.0,
    "compare": null,
    "color": "White / Total Orange / Black",
    "image": "https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto%2Cu_9ddf04c7-2a9a-4d76-add1-d15af8f0263d%2Cc_scale%2Cfl_relative%2Cw_1.0%2Ch_1.0%2Cfl_layer_apply/b691de5f-50fb-414e-9c04-d48764e13ef0/AIR%2BZOOM%2BPEGASUS%2B42.png",
    "source": "Nike",
    "source_url": "https://www.nike.com/t/pegasus-42-mens-road-running-shoes-S1bYkOza/IZ6178-101"
  },
  {
    "id": 1,
    "name": "Nike Vaporfly 4",
    "brand": "Nike",
    "category": "Running Shoes",
    "type": "Race Day",
    "gender": "Men",
    "price": 270.0,
    "compare": null,
    "color": "Blue / White",
    "image": "https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto%2Cu_9ddf04c7-2a9a-4d76-add1-d15af8f0263d%2Cc_scale%2Cfl_relative%2Cw_1.0%2Ch_1.0%2Cfl_layer_apply/ffe50641-aab4-4397-8f76-2ca16aee3d0e/ZOOMX%2BVAPORFLY%2BNEXT%25%2B4%2BFK.png",
    "source": "Nike",
    "source_url": "https://www.nike.com/us/es/t/tenis-de-carrera-en-pavimento-vaporfly4-HK05JWOf/IM8203-400"
  },
  {
    "id": 2,
    "name": "adidas Adizero Boston 13",
    "brand": "adidas",
    "category": "Running Shoes",
    "type": "Speed Trainer",
    "gender": "Men",
    "price": 160.0,
    "compare": null,
    "color": "White / Black / Red",
    "image": "https://assets.adidas.com/images/w_1880%2Cf_auto%2Cq_auto/0b7c71ea1642448281858d43b1089a2c_9366/JS4932_01_00_standard.jpg",
    "source": "adidas",
    "source_url": "https://www.adidas.com/us/adizero_boston-shoes"
  },
  {
    "id": 3,
    "name": "adidas Adizero Adios Pro 4",
    "brand": "adidas",
    "category": "Running Shoes",
    "type": "Race Day",
    "gender": "Unisex",
    "price": 204.0,
    "compare": 255.0,
    "color": "White / Black",
    "image": "https://assets.adidas.com/images/w_1880%2Cf_auto%2Cq_auto/1f42c7cb7e05440597288cc498388dce_9366/JR1094_HM51.jpg",
    "source": "adidas",
    "source_url": "https://www.adidas.com/us/adizero_adios_pro_4"
  },
  {
    "id": 4,
    "name": "HOKA Clifton 10",
    "brand": "HOKA",
    "category": "Running Shoes",
    "type": "Daily Trainer",
    "gender": "Men",
    "price": 124.0,
    "compare": 155.0,
    "color": "Yellow / Teal",
    "image": "https://dms.deckers.com/hoka/image/upload/t_slider-grid-tile-wp/v1773159836/1162030-YDT_1.png?_s=RAABAB0",
    "source": "HOKA",
    "source_url": "https://www.hoka.com/en/us/mens-everyday-running-gear/clifton-10/1162030.html"
  },
  {
    "id": 5,
    "name": "Brooks Ghost 18",
    "brand": "Brooks",
    "category": "Running Shoes",
    "type": "Daily Trainer",
    "gender": "Men",
    "price": 150.0,
    "compare": null,
    "color": "Coconut / Pearl / Tigerlily",
    "image": "https://www.brooksrunning.com/dw/image/v2/BGPF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dw43d61a5c/original/110493/110493-292-l-ghost-18-mens-neutral-cushion-running-shoe.jpg?bgcolor=F8F8F8&sfrm=png&sh=425&sm=fit&strip=false&sw=425",
    "source": "Brooks Running",
    "source_url": "https://www.brooksrunning.com/en_us/mens/shoes/road-running-shoes/ghost-18/110493.html"
  },
  {
    "id": 6,
    "name": "Saucony Endorphin Speed 5",
    "brand": "Saucony",
    "category": "Running Shoes",
    "type": "Speed Trainer",
    "gender": "Men",
    "price": 129.95,
    "compare": 175.0,
    "color": "White / Black / Citron",
    "image": "https://thekit.wolverineworldwide.com/match/media_lookup/S21007-95_1/?preset=dw-pdp-primary",
    "source": "Nordstrom / Saucony",
    "source_url": "https://www.nordstrom.com/s/saucony-endorphin-speed-5-running-shoe-men/8106509"
  },
  {
    "id": 7,
    "name": "Feetures Elite Light Cushion Mini Crew 3-Pack",
    "brand": "Feetures",
    "category": "Socks",
    "type": "Running Socks",
    "gender": "Unisex",
    "price": 59.85,
    "compare": 63.0,
    "color": "USA Mix",
    "image": "https://feetures.com/cdn/shop/files/Elite_LC_MiniCrew_USA_3pk_1.jpg?v=1773424542&width=1600",
    "source": "Feetures",
    "source_url": "https://feetures.com/products/elite-light-cushion-mini-crew-3-pack"
  },
  {
    "id": 8,
    "name": "Balega Hidden Comfort No Show 3-Pack",
    "brand": "Balega",
    "category": "Socks",
    "type": "Running Socks",
    "gender": "Unisex",
    "price": 48.45,
    "compare": 51.0,
    "color": "White",
    "image": "https://balega.com/cdn/shop/files/BALE_0000_HiddenComfortWhite.jpg?crop=center&height=1200&v=1742936203&width=1200",
    "source": "Balega",
    "source_url": "https://balega.com/products/3-pack-hidden-comfort-no-show-tab"
  },
  {
    "id": 9,
    "name": "Nike Dri-FIT Club Structured Swoosh Cap",
    "brand": "Nike",
    "category": "Hats",
    "type": "Performance Cap",
    "gender": "Unisex",
    "price": 28.0,
    "compare": null,
    "color": "Black / White",
    "image": "https://content.stylitics.com/images/items/17805635",
    "source": "Nike",
    "source_url": "https://www.nike.com/t/dri-fit-club-structured-swoosh-cap-kxvJ3j/FB5625-010"
  },
  {
    "id": 10,
    "name": "goodr Astro G Sunglasses",
    "brand": "goodr",
    "category": "Sunglasses",
    "type": "Running Sunglasses",
    "gender": "Unisex",
    "price": 45.0,
    "compare": null,
    "color": "Mirrored Performance Lens",
    "image": "https://content.backcountry.com/images/items/small/GDO/GDO005K/MYSWHAANOCRA.jpg",
    "source": "Backcountry",
    "source_url": "https://www.backcountry.com/goodr-astro-g-sunglasses"
  },
  {
    "id": 11,
    "name": "FlipBelt Classic Running Belt",
    "brand": "FlipBelt",
    "category": "Belts",
    "type": "Phone & Key Belt",
    "gender": "Unisex",
    "price": 44.0,
    "compare": null,
    "color": "Black",
    "image": "https://flipbelt.com/cdn/shop/files/3_38cbd835-aece-46a6-91a5-dff49dd4e7de.png?v=1771357877&width=2000",
    "source": "FlipBelt",
    "source_url": "https://flipbelt.com/products/flipbelt-classic-running-belt"
  },
  {
    "id": 12,
    "name": "FlipBelt Zipper Running Belt",
    "brand": "FlipBelt",
    "category": "Belts",
    "type": "Secure Running Belt",
    "gender": "Unisex",
    "price": 49.0,
    "compare": null,
    "color": "Black",
    "image": "https://flipbelt.com/cdn/shop/files/10_10c90ab3-3438-4912-a44e-14f260e30c03.png?v=1770764748&width=2000",
    "source": "FlipBelt",
    "source_url": "https://flipbelt.com/products/flipbelt-zipper-running-belt"
  },
  {
    "id": 13,
    "name": "On Soft Flask 500ml",
    "brand": "On",
    "category": "Hydration",
    "type": "Soft Flask",
    "gender": "Unisex",
    "price": 25.0,
    "compare": null,
    "color": "Translucent / Black",
    "image": "https://images.ctfassets.net/hnk2vsx53n6l/1w89ON7pGtVZBW6tcUzCwy/994554e9711703a86187f143d8ecf421/4ee1d5011d768e31ff3b5c84d5bfc84852185b7b.jpg?fm=webp",
    "source": "On",
    "source_url": "https://www.on.com/en-us/products/soft-flask-500ml-u-2ue1037/unisex/translucent-black-accessories-2UE10372795"
  }
];